config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users
  resources :friends

  resources :projects do
    resources :tasks, only: [:index]
  end

  root 'home#index'
end

app/models/task.rb
class Task < ApplicationRecord
	enum status: {brand_new: 0, in_process: 1, waiting_for_client: 2, done: 3}
	belongs_to :project
	belongs_to :user
	has_many_attached :files
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:subject, :description, :user_id, :project_id, :status, files: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :subject
    = f.input :description
    = f.label :user_id
    %br
    = f.collection_select :user_id, User.all, :id, :email, prompt: true, placeholder: "User"
    %br
    %br
    = f.label :project_id
    %br
    = f.collection_select :project_id, Project.all, :id, :nazev, prompt: true
    %br
    %br
    = f.label :files, "Files"
    = f.file_field :files, multiple: true, direct_upload: true
    %br
    - if task.persisted?
      %br
      = f.label :status
      %br
      = f.select :status, Task.statuses.keys
  %br

  .form-actions
    = f.button :submit, class: "btn btn-secondary"

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Subject:</strong>
    <%= task.subject %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= task.user_id %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/_task.html.haml
%div{id: "#{dom_id(task)}"}
  %p
    %strong Subject:
    = task.subject
  %p
    %strong Description:
    = task.description
  %p
    %strong User:
    = task.user_id
  %p
    %strong Project:
    = task.project_id

app/views/tasks/edit.html.haml
%h1 Editing task

= render "form", task: @task

%br

%div
  = link_to "Show this task", @task

app/views/tasks/index.html.haml
%p{ style: "color: green" }= notice

%h1 Tasks for #{@project.nazev}

#tasks
  - if user_signed_in?
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Subject
          %th Description
          %th Status
          %th{:colspan => "2"}
      %tbody
        - @tasks.each do |task|
          %tr
            %td.align-middle= task.subject
            %td.align-middle= task.description
            %td.align-middle= task.status
            %td.text-center= link_to "Show", task, class: "btn btn-outline-info btn-sm"
            %td.text-center= link_to "Edit", edit_task_path(task), class: "btn btn-outline-primary btn-sm"
            %td.text-center= link_to 'Delete', task, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm"
    = link_to "New task", new_task_path, class: "btn btn-secondary"

app/views/tasks/new.html.haml
%h1 New task

= render "form", task: @task

app/views/tasks/show.html.haml
%p{style: "color: green"}= notice

%div.p-5.mb-4.bg-body-tertiary.rounded-3
  .container-fluid.py-5
    %h1.display-5.fw-bold
      = @task.subject
    %br/
    %p.col-md-5.fs-4
      = @task.description
    %p.col-md-auto
      - if @task.files.attached?
        -@task.files.map do |file|
          = link_to image_tag(file, class: "mx-1 my-1 object-fit-cover", style: "height: 300px; width:300px;"), url_for(file)
    = link_to "Edit this task", edit_task_path(@task), class: "btn btn-secondary"
    |
    = link_to "Back to projects", projects_path, class: "btn btn-dark"