config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users
  resources :friends

  resources :projects do
    resources :tasks, only: [:index]
  end

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless session[:redirected]
      redirect_to new_user_registration_path
      session[:redirected] = true
    else
      @in_process_tasks = Task.where(status: Task.statuses[:in_process]).pluck(:subject)

      @done_tasks = Task.where(status: Task.statuses[:done]).pluck(:subject)

      @projects_with_tasks = Project.joins(:tasks).distinct
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.haml
.navbar.navbar-expand-lg.bg-body-tertiary
  .container-fluid
    = link_to 'Project management system', root_path, class: "navbar-brand"
    %button.navbar-toggler{"type": "button", "data-bs-toggle": "collapse", "data-bs-target": "#navbarSupportedContent", "aria-controls": "navbarSupportedContent", "aria-expanded": "false", "aria-label": "Toggle navigation"}
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      - if user_signed_in?
        %ul.navbar-nav
          %li.nav-item
            = link_to 'Projects', projects_path, class: "nav-link"
        %ul.navbar-nav
          %li.nav-item
            = link_to 'Users', users_path, class: "nav-link"
        %ul.navbar-nav
          %li.nav-item
            = link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            = link_to 'Edit profile', edit_user_registration_path, class: "nav-link"
      - else
        %ul.navbar-nav
          %li.nav-item
            = link_to 'Sign up', new_user_registration_path, class: "nav-link"
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            = link_to 'Sign in', new_user_session_path, class: "nav-link"
      %form.d-flex
      -if user_signed_in?
        - if current_user.name and current_user.surname
          %b= current_user.name + " " +current_user.surname
        - if current_user.image.attached?
          = image_tag(current_user.image, class: "mw-100 rounded-circle object-fit-cover border border-5 border-success", style: "height: 50px; width:50px; margin: 0 50px 0 15px;")
          %br/
        - else

app/views/home/index.html.haml
%h1.text-center Homepage
%br
- if user_signed_in?
	.row
		.col-md-8
			%h2 Projects creating activity:
			= line_chart Project.group_by_day(:created_at).count
		.col-md
			%h2 Count of task statuses:
			= pie_chart Task.group(:status).count
	%br
	%br
	.row
		.col-md
			.row
				.col
					%h2 These tasks are currently in process:
					%br
					- if @in_process_tasks.present?
						- @in_process_tasks.each do |task_subject|
							%ul
								%li= task_subject
					- else
						%p No tasks in process at the moment.
			.row
				.col-md
					%h2 These tasks are currently done:
					%br
					- if @done_tasks.present?
						- @done_tasks.each do |task_subject|
							%ul
								%li= task_subject
					- else
						%p No tasks done at the moment.
		.col-md
			%h2 Projects with 1 and more tasks:
			- if @projects_with_tasks.present?
				- @projects_with_tasks.each do |project|
					%ul
						%li= project.nazev
			- else
				%p No projects with tasks at the moment.
	%br
	%br