config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users
  resources :friends

  resources :projects do
    resources :tasks, only: [:index]
  end

  root 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
	 validates :nazev, presence: true
	 has_many :tasks, dependent: :restrict_with_exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy

    if @project.tasks.empty?
      @project.destroy
      redirect_to projects_url, notice: "Project was successfully destroyed."
    else
      redirect_to projects_url, alert: "Project cannot be deleted as it has associated tasks."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:nazev, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  
  = f.input :nazev, placeholder: 'Name', label: false, input_html: { class: 'form-control' }
  = f.input :description, placeholder: 'Description', label: false, input_html: { class: 'form-control' }
  
  = f.button :submit, class: 'btn btn-secondary'

app/views/projects/edit.html.haml
%h1 Editing project

= render "form", project: @project

%br

%div
  = link_to "Back", projects_path, class: "btn btn-dark"
  = link_to "Show project", @project, class: "btn btn-dark"
  = link_to 'Delete project', @project, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/projects/index.html.haml
#projects
  - if user_signed_in?
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Name
          %th Date of creation
          %th Number of Tasks
          %th{:colspan => "2"}
      %tbody
        - @projects.each do |project|
          %tr
            %td.align-middle
              = link_to project.nazev, project_tasks_path(project)
            %td.align-middle
              = project.created_at
            %td.align-middle
              = project.tasks.count
            %td.text-center
              = link_to "Show", project, class: "btn btn-outline-info btn-sm"
            %td.text-center
              = link_to "Edit", edit_project_path(project), class: "btn btn-outline-primary btn-sm"
            %td.text-center
              = link_to 'Delete', project, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm"
    = link_to "New project", new_project_path, class: "btn btn-secondary"

app/views/projects/new.html.haml
%h1 New project

= render "form", project: @project

%br

%div
  = link_to "Back", projects_path, class: "btn btn-dark"

app/views/projects/show.html.haml
%p{style: "color: green"}= notice

%div.p-5.mb-4.bg-body-tertiary.rounded-3
  .container-fluid.py-5
    %h1.display-5.fw-bold
      = @project.nazev
    %br/
    %p.col-md-8.fs-4
      = @project.description
    = link_to "Edit this project", edit_project_path(@project), class: "btn btn-secondary"
    |
    = link_to "Back to projects", projects_path, class: "btn btn-dark"
    |
    = link_to 'Delete project', @project, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger"